# Generated by Django 4.2.5 on 2023-11-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(
                upload_to="project_image/", verbose_name="projects"
            ),
        ),
    ]
