# Generated by Django 4.2.5 on 2023-11-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75)),
                ("age", models.SmallIntegerField()),
                ("experience", models.TextField()),
                (
                    "ebalo",
                    models.ImageField(upload_to="roga/", verbose_name="personal-image"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=35, unique=True)),
                ("descriptions", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        upload_to="rate-image/", verbose_name="rate-image"
                    ),
                ),
                ("price", models.IntegerField()),
                ("term", models.CharField(max_length=55)),
                ("create_ed", models.DateTimeField(auto_now=True)),
                ("update_ed", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
